version: 0.2

phases:
  pre_build:
    commands:
      - echo Logare in Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 029139774173.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=029139774173.dkr.ecr.eu-central-1.amazonaws.com/adunare-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build inceput la data de `date`
      - echo Constructie imagine Docker...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build finalizat la data de `date`
      - echo Push imagine in ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Scriere fisier de definitie pentru deploy...
      - printf '[{"name":"adunare-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
